[lint]
select = ["E", "F", "I"]
ignore = ["E501"]

# isort configuration
[lint.isort]
known-third-party = ["pandas", "matplotlib", "numpy"]
#default-section = "THIRDPARTY"
combine-as-imports = true
force-wrap-aliases = true
force-single-line = true
